module.exports = {
  apps: [
    {
      name: "todo-app",
      script: "npm",
      args: "run start",
      instances: "max",
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      error_file: "./logs/error.log",
      out_file: "./logs/out.log",
      log_file: "./logs/combined.log",
      time_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_memory_restart: "1G",
      watch: false,
      ignore_watch: ["node_modules", ".next", "logs"],
      listen_timeout: 3000,
      kill_timeout: 5000,
    },
    {
      name: "realtime",
      script: "node",
      args: "realtime-server.cjs",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      error_file: "./logs/realtime-error.log",
      out_file: "./logs/realtime-out.log",
      merge_logs: true,
      autorestart: true,
      max_memory_restart: "512M",
      watch: false,
      listen_timeout: 3000,
      kill_timeout: 5000,
    },
  ],
  deploy: {
    production: {
      user: "deploy",
      host: "<your-domain.com>",
      ref: "origin/main",
      repo: "git@github.com:yourorg/sf-project-task.git",
      path: "/home/deploy/apps/todo",
      "post-deploy": "pnpm install && pnpm build && pm2 reload ecosystem.config.js --env production",
      "pre-deploy-local": 'echo "Deploying to production server"',
    },
  },
};
